<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Key Attributes of an MVP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">RCP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html" rel="" target="">
 <span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf" rel="" target="">
 <span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" rel="" target="" aria-current="page">
 <span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-literature-review" id="toc-introduction-literature-review" class="nav-link active" data-scroll-target="#introduction-literature-review">Introduction &amp; Literature Review</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#ethics" id="toc-ethics" class="nav-link" data-scroll-target="#ethics">Ethics</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Key Attributes of an MVP</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-literature-review" class="level3">
<h3 class="anchored" data-anchor-id="introduction-literature-review">Introduction &amp; Literature Review</h3>
<p>As Duke University students, we are very interested and invested in basketball. Each year, Duke sends basketball players to the NBA and many perform very well throughout their professional careers. Our group is interested in what distinguishes good players in the NBA from great, exceptional players. Particularly, how is a single MVP chosen from hundreds of professional basketball players each season?</p>
<p>We considered Vivek Datta’s findings during our research on this topic, which he details in “Evolution of the NBA” <span class="citation" data-cites="Datta2018">(<a href="#ref-Datta2018" role="doc-biblioref">Datta 2018</a>)</span> Written in 2018, this article articulates the progression of NBA individual players, teams, and rules from 1976 to 2018. Datta explains that offense has become less structured and more fast-paced over the aforementioned time period; offenses previously depended on larger men to score, but now primarily rely on three-pointers. This forces the defense to spread out, and larger men must therefore have greater agility to guard smaller guards. Further, the NBA shifted to a prohibition of hand-checking, which is the defender’s use of hands and arms to prevent an offensive player from moving forward. This change has enabled smaller players to be more competitive by reducing contact and increasing perimeter (mid-range) shots. These factors, coupled with many others Datta discusses, have a large impact on player performance and subsequent effect on MVP selection criteria.</p>
<p>While Datta’s study investigates the 1976-2018 seasons, his research is broader than our interests. He focuses on large-scale trends between offense and defense in his analysis. We want to focus more on the qualities that best predict MVPs rather than changes to the overall game and will thus investigate the 1997-2022 seasons to identify emerging trends in MVP selection criteria.</p>
</section>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p>Our research question for this dataset is the following: Which qualities are the best predictors of NBA MVP status in the 1997-2022 seasons? This question is important as the NBA MVP award is the highest honor for an NBA player; many players work for most of their lives to achieve this award, and people of all ages admire those who earn the MVP award. It is important to have an understanding of why each MVP is selected and how he is different from those who precede and succeed him, so we can ensure the selection process has not become more arbitrary or reliant on factors outside of on-court performance over time.</p>
<p>A panel of members of the sports media chosen by the NBA vote to decide the regular season NBA MVP. Although the panelists are knowledgeable about basketball, the MVP selection process is subjective. Our project aims to determine what skills NBA MVP selection panelists value. We will compare MVPs from different years and compare MVPs to other players in the same season to find in which categories the MVP excelled or struggled. For the 1997-2022 basketball seasons, we hypothesize that the number of three-pointers per game is one of the best MVP predictors and that most of the best MVP predictors are related to offensive categories.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>Our data comes from NBA players’ game day statistics provided by the Basketball Reference website. This data was collected from the 1997-1998 season through the 2021-2022 season; it was organized by Eduardo Tocco, an information science and Tech student at the University of Arizona. Tocco was able to collect this public data as it had already been published by the NBA; more specifically, he scraped the data above from the site Basketball Reference which uses official NBA data. Our dataset is made up of 14,753 entries (rows) and 31 total columns. Each observation represents a player/year combination. Each observation also contains additional information on player position, age, team, and various basketball-related statistics. The statistics relevant to this project are described below.</p>
<ul>
<li><p><em>MVP</em> - Reports True or False; indicates whether an observation (a player in a given year) won the MVP (True = Yes, False = No).</p></li>
<li><p><em>Average Points per Game</em></p></li>
<li><p><em>Average Minutes Played per Game</em></p></li>
<li><p><em>Number of Games Played</em></p></li>
<li><p><em>Average Field Goals per Game</em> - field goals are baskets made on any shot other than a free throw.</p></li>
<li><p><em>Position</em> - there are five possible positions: center, power forward, small forward, point guard, and shooting guard.</p></li>
<li><p><em>Field Goal Percentage</em> - the ratio of field goals made to field goals attempted.</p></li>
<li><p><em>Number of Games Started</em> - “Started” means the player was in the first squad of 5 players to play on the court at the beginning of the game.</p></li>
<li><p><em>2-Pointer Percentage</em> - the ratio of 2-point shots made to 2-point shots attempted</p></li>
<li><p><em>Average Assists per Game</em> - an assist is when a player passes the ball to a teammate who then proceeds to make a field goal.</p></li>
<li><p><em>Average Blocks per Game</em> - a block is when a defensive player successfully prevents a field goal attempt from an offensive player.</p></li>
</ul>
</section>
<section id="ethics" class="level3">
<h3 class="anchored" data-anchor-id="ethics">Ethics</h3>
<p>Though seemingly minor, when collecting/compiling/re-publishing data, it is essential that those collecting (in this case Eduardo Tocco) act ethically responsible by granting proper credit to the original source of the data (NBA). Moreover, although the original data was public, players and others relevant to the data should be kept informed when re-collecting and re-analyzing the statistics in different contexts; those compiling already public information should also still take into consideration the mental impact on players when stats from old games are being re-publicized and re-analyzed in new and different ways. In this case, it is especially true because the information relates to mistakes made in games and other emotion-provoking information that may impact player morality, well-being, and public relations.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>When the data was first read into RStudio, some changes were made to make the data set more workable.</p>
<ol type="1">
<li>Variables that began with numbers (ex. 3P, which represents average three-pointers per game) were renamed to begin with letters (ex. threeP). This allowed for the variables to be read into data visualizations.</li>
</ol>
<ol start="2" type="1">
<li>The MVP variable was converted from a boolean to a factor and leveled such that the ordering was False then True. This ordering was chosen so that the logistic model (explained in future sections) would output probabilities of MVP status being True.</li>
</ol>
<ol start="3" type="1">
<li>A separate data set was also created that contained only the MVP winners (in the season they won the award). This allowed for data visualization and data re-balancing (explained in Methodology Part 2).</li>
</ol>
<section id="part-1-exploring-the-data-set" class="level4">
<h4 class="anchored" data-anchor-id="part-1-exploring-the-data-set">Part 1: Exploring the Data Set</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">MVP Status</th>
<th style="text-align: center;">Number of Observations</th>
<th style="text-align: center;">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">FALSE</td>
<td style="text-align: center;">14548</td>
<td style="text-align: center;">99.8284499</td>
</tr>
<tr class="even">
<td style="text-align: center;">TRUE</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">0.1715501</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table above shows that the number of non-MVPs in the dataset vastly outnumbers the number of MVPs. Over 99.8% of the dataset is non-MVPs, while only .17% is MVPs.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/avg-points-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">MVP Status</th>
<th style="text-align: center;">Median Average Points Per Game</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">MVP</td>
<td style="text-align: center;">27.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Non-MVP</td>
<td style="text-align: center;">6.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The boxplot above compares the average points per game of MVPs and non-MVPs. There is a distinct difference in the average points scored per game across the two groups. The table confirmed this data: MVP winners (in the season they won the MVP) had a median score of 27.1 points per game on average, but non-MVP winners had a median score of 6.4 points per game on average. That is over a 4-fold difference in the median average points scored per game!</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/avg-minutes-visualization-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">MVP Status</th>
<th style="text-align: center;">Median Average Playing Time (Minutes)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">MVP</td>
<td style="text-align: center;">37.4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Non-MVP</td>
<td style="text-align: center;">18.9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The boxplot above compares the average minutes played per game of MVPs and non-MVPs. There is a distinct difference in the average minutes played per game across the two groups. However, in the non-MVP group, there is a much higher spread and much more variability in the data compared to the MVP group (likely due in part to a much higher number of observations). The table quantifies this data: MVP winners had a median average playing time of 37.4 minutes per game, and non-MVP winners had a median average playing time of 18.9 minutes per game. That is approximately a 2-fold difference in median average playing time per game!</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/position-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The barplot above depicts the distribution of positions of only MVP winners. As the data shows, shooting guards, small forwards, and centers had about 3-4 MVP winners each from the 1997-2022 NBA seasons, and point guards and power forwards had slightly more MVP winners (6 and 8 MVP winners each, respectively) during that same time period. Unfortunately, because the data set of MVP winners is so small, it is difficult to draw conclusions from this data about whether certain positions are more likely to win the MVP award compared to others.</p>
<p>The data explorations above support the following conclusions:</p>
<ol type="1">
<li><p>The data set is very unbalanced. There is a disproportionate amount of non-MVP winners in the data set compared to MVP winners</p></li>
<li><p>High average points per game and high average playing time may be good indicators of MVP status.</p></li>
<li><p>No conclusions can be drawn about which positions are more or less likely to win MVP status.</p></li>
</ol>
<p>Given these conclusions, we felt it was best to attempt to re-balance the data set before moving forward in our exploration. This is because our ultimate goal is to be able to predict MVP winners. When a data set is so unbalanced and the MVP winners are very diluted, it can be difficult to pick out trends within the data and build a model to predict whether a player is an MVP winner (as the model would default to non-MVP status due to the sheer quantity of those observations). Therefore, we re-balance the data set in the following section in an attempt to mitigate this issue.</p>
</section>
<section id="part-2-re-balancing-the-data-set" class="level4">
<h4 class="anchored" data-anchor-id="part-2-re-balancing-the-data-set">Part 2: Re-balancing the Data Set</h4>
<p>As mentioned previously, we are interested in identifying what differentiates MVPs from all other NBA basketball players. Thus, it makes sense that in order to understand the difference between good and great players, we choose a subset of excellent players for our smaller data set. Thus, we chose to re-balance our data set based on average points per game and average minutes played per game because those variables were previously shown to be higher in MVPs than non-MVPs.</p>
<p>First, we created a data set that contained the top 5 players with the highest average points per game for each season. Second, we created a data set that contained the top 5 players with the highest average playing time per game for each season. Then, we merged the data sets, keeping all observations from both data sets. If a given player-year observation was in both of the top 5 data sets, others were not added in. This decision was made to keep the size of the data set reasonably small. Finally, we merged the data set with the data set containing only the MVP winners.</p>
<p>The final data set contained 222 unique observations with the highest average scorers, the players with the most average playing time, and the MVPs from each season from the 1997-1998 season through the 2021-2022 season. This is much smaller than the original data set that contained 14,573 observations.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">MVP Status</th>
<th style="text-align: center;">Number of Observations</th>
<th style="text-align: center;">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">FALSE</td>
<td style="text-align: center;">197</td>
<td style="text-align: center;">88.73874</td>
</tr>
<tr class="even">
<td style="text-align: center;">TRUE</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11.26126</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As the table shows above, in the new data set, 11.3% of observations are MVP winners, and 88.7% are non-MVP winners. There is still an imbalance between MVP and non-MVP winners, but much less so compared to the original data set.</p>
</section>
<section id="part-3-main-methodology" class="level4">
<h4 class="anchored" data-anchor-id="part-3-main-methodology">Part 3: Main Methodology</h4>
<p>Now that we have re-balanced our data set, we plan to gain a more comprehensive understanding of which variables are best predictors of MVP status among these competitive players. As mentioned in our introduction, there are a variety of quantitative variables this data set provides, such as average steals per game, average defensive rebounds per game, average offensive rebounds per game…etc. There are 28 such columns that provide different statistics about a given player for a given season.</p>
<p>To answer our research question, we plan to build a logistic model that predicts the log odds of a given player-year observation being an MVP. The model with the lowest AIC is the combination of variables that best predicts the log odds of MVP status. The stepAIC is a method used for stepwise model selection. Given a data set and a set of variables, it can iterate through all combinations of such variables to identify which combination of variables provides the best logistic model to predict MVP status. We plan to use this stepAIC to determine which variables and what combination of them are best predictors of MVP status.</p>
<p>We then plan to assess the performance of this model. We will test the model on a portion of the data set it has not been trained on. A confusion matrix will be used to visualize the results. In particular, the matrix will display the number of true positives, true negatives, false positives, and false negative outcomes of the model.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>First, we split our data set into a training data set and testing data set. The training data set contains 80% of the observations and will be used to train the model. The testing data set contains 20% of the observations and will be used to test the model.</p>
<p>Then, we performed a forward stepAIC using the 26 basketball statistic variables from the data set to pick the “best” overall model for predicting MVP Status. All variables were input into the model. The model output is written below. The model gives the log odds of a player-year observation being an MVP given their statistics for the variables in the equation. The AIC for this model is 81.16.</p>
<span class="math display">\[\begin{align*}
\log\Big(\frac{\hat{p}}{1-\hat{p}}\Big) = -31.00 + 0.6400 \times PTS + 103.1 \times FGPerc +
0.8510\times AST \\- 62.26 \times twoPPerc - 1.318 \times FG + 18.05 \times GS
-18.03 \times G + 0.8793 \times BLK
\end{align*}\]</span>
<p>The following explanatory variables were included in the best-fit additive model: average points per game, field goal percentage, average steals per game, 2-pointer percentage, average field goals per game, number of games started, number of games played, and average blocks per game.</p>
<p>Holding other variables constant, variables with positive coefficients (ex. average points per game and field goal percentage) indicate an increase in such statistics increase the log odds of being MVP. On the other hand, variables with negative coefficients (ex. 2-pointer percentage and average and number of games played) indicate an increase in such statistics decreases the log odds of being MVP.</p>
<p>Additionally, certain variables have higher coefficients than others. This means that for a 1 unit increase in a given variable, we estimate on average a higher increase in the log odds of MVP status than that of a variable with a lower coefficient (holding all other variables constant). For instance, a 1 unit increase in field goal percentage (coefficient of 103.1) increases the log odds of MVP status more than a 1 unit increase in average blocks per game (coefficient of 0.8793).</p>
<p>Overall, this model identifies the 8 predictors that best predict MVP status from the input data set, which answers our central research question. It also tells us whether an increase in those predictors increases or decreases the log odds of MVP status and how much we estimate on average each variable changes the log odds of MVP status per a 1 unit change in that variable.</p>
<section id="assessing-the-predictive-strength-of-the-model" class="level4">
<h4 class="anchored" data-anchor-id="assessing-the-predictive-strength-of-the-model"><strong>Assessing the Predictive Strength of the Model</strong></h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/training-and-testing-data-split-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The confusion matrix above shows the model results on the testing data set. Given that a player-year observation is an MVP, the model correctly predicts this 16.67% of the time. This indicates the sensitivity of the model is low. Given a player-year observation is not an MVP, the model correctly predicts this 89.74% of the time. This indicates the specificity of the model is high.</p>
<p>The F-1 score of this model is .1818. F-1 score was chosen as a metric to evaluate the model because it is a good metric for imbalanced data. Ideally, F-1 scores should be high (close to 1). Our low F-1 score indicates this model has weak overall performance.</p>
<p>This serves to qualify the validity of the answer to our research question above (the 8 proposed best predictors from our model) as it suggests the model is not very reliable.</p>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<p>The goal of our data analysis was to pinpoint the qualities that the NBA values the most when selecting an MVP. We hypothesized that the average number of three-pointers per game would be one of the best MVP predictors and that most of the best MVP predictors are related to offense. To find the best model for predicting MVPs, we used step-wise logistic regression, which outputted the model with the following explanatory variables: average points per game, field goal percentage, number of games started, 2-pointer percentage, average assists per game, average field goals per game, number of games played, and average blocks per game has the lowest AIC. Since the average number of three-pointers per game is not among these eight best predictors of MVP status, that part of our hypothesis was not supported. However, many of the variables the model outputted were related to offense (ex. average points per game, field goal percentage, average assists per game), which supports that component of our hypothesis.</p>
<p>Furthermore, our confusion matrix assessed the predictive strength of the model generated from the stepAIC procedure. Our output indicated that our model was a relatively poor predictor of MVP status. This is likely in part because our data set was still largely unbalanced, despite efforts to re-balance it. The weakness of our model tells us we can not conclude the 8 variables outputted by the model are confidently the best predictors of MVP status. Rather, further statistical analysis is required to verify and refine these findings.</p>
</section>
<section id="reliability-validity-of-data" class="level4">
<h4 class="anchored" data-anchor-id="reliability-validity-of-data">Reliability &amp; Validity of Data</h4>
<p>It is important to consider the reliability and validity of our data. Our data on offensive statistics being strong predictors of MVP status makes sense given what we know in the context of the NBA. The NBA has a strong emphasis on offensive performance. This helps to validate some of our findings. In terms of reliability of the data, the NBA has automated systems for collecting player statistics and cameras installed in the catwalks of every NBA arena. Furthermore, Second Spectrum software tracks the movements of every player on the court and the basketball 25 times per second. This strengthens the reliability of the data, given the rigor at which it is collected.</p>
<p>To expand on the reliability and validity of our data, we chose our re-balance our data set based on the average points per game and average minutes played per game. In retrospect, while average points per game was one of the 8 predictors of the model output, average minutes played per game was not. This indicates the data set input into the model could have made the model less reliable. In the future, the data set could be subset based on field goal percentage and number of games started, as those two variables had high positive coefficients, meaning per 1 unit increase in those variables, they most increased the log odds of MVP status compared to the other variables.</p>
</section>
<section id="scope-of-inference" class="level4">
<h4 class="anchored" data-anchor-id="scope-of-inference">Scope of Inference</h4>
<p>The scope of inference is relatively limited to the NBA at the current time range. The NBA differs from the WNBA and the EuroLeague in that the NBA is much more offensively focused, which means the skills valued in an MVP in one league may not transfer over to the other leagues. In these cases, other leagues may place more value on defensive qualities, such as average blocks or steals per game, which may be better predictors of MVP status. The scope of inference is also limited by time. Although not explored in this project, it is likely that the qualities that the NBA values change over time, meaning a model that successfully predicts MVPs from the 1997-2022 seasons may not be as relevant in future years.</p>
</section>
<section id="limitations-future-areas-of-research" class="level4">
<h4 class="anchored" data-anchor-id="limitations-future-areas-of-research">Limitations &amp; Future Areas of Research</h4>
<p>A limitation touched upon in the previous subsection was how our findings may not translate through time given the changing nature of valued MVP qualities. To contemporize our findings, we can collect data from upcoming NBA seasons and add them to the data set to see how new players and seasons affect our findings.</p>
<p>Another central limitation of our project is the imbalance in our data set between MVPs and non-MVPs. While this will always be an issue due to the inherent selectivity of the award, this issue can be minimized by performing analyses on only MVP-nominated players across many seasons. This could help to better assess what makes MVP winners stand out amongst other MVP nominees while keeping the data set size relatively small.</p>
<p>An area for future research and exploration is using a different type of logistic model. In this project, we fit a step-wise additive model, but we also could have fit an interactive model. This interactive model would add a layer of complexity to the model by exploring how multiple variables interact with one another to influence MVP status. If the AIC of the interactive model is lower than that of the additive model, it may help to better predict the likelihood of MVP status.</p>



</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Datta2018" class="csl-entry" role="listitem">
Datta, Vivek. 2018. <span>“Evolution of the NBA.”</span> <em>Sports Analytics Group Berkley</em>. <a href="https://sportsanalytics.berkeley.edu/articles/nba-evolution.html">https://sportsanalytics.berkeley.edu/articles/nba-evolution.html</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>